from __future__ import annotations

from pathlib import Path
import shutil

from core.domains import DomainAdapter
from core.long_horizon.acceptance_contract import AcceptanceContract, GoalCriterion
from core.models import Plan, SubTask
from core.tools.file_editor import FileEditor
from core.tools.shell_runner import ShellRunner
from core.tools.test_runner import TestRunner
from domains.software_agents import build_software_agents


WORKSPACE = "examples/software_task"
PYTEST_COMMAND = "python -m pytest test_app.py -q -p no:cacheprovider"

INITIAL_APP = """def add(a, b):
    return b - a
"""

TEST_APP = """import pytest

from app import add


def test_add_positive_numbers():
    assert add(1, 2) == 3


def test_add_negative_numbers():
    assert add(-4, -6) == -10


def test_add_zero():
    assert add(5, 0) == 5


def test_add_float_numbers():
    assert add(0.1, 0.2) == pytest.approx(0.3)
"""

REQUIREMENTS = """# Software Requirement

## Goal

Repair the supplied Python calculator module.

## Requirement

The `add(a, b)` function must return the arithmetic sum of its two inputs.

## Acceptance Criteria

1. The exact command `python -m pytest test_app.py -q -p no:cacheprovider` exits with code 0.
2. The repaired source and software report are generated by the current run.
"""


class SoftwareDomainAdapter(DomainAdapter):
    name = "software"

    def register_tools(self, registry, workspace):
        shell_runner = ShellRunner(workspace)
        registry.register(FileEditor(workspace))
        registry.register(shell_runner)
        registry.register(TestRunner(shell_runner))

    def build_agents(self, model_client, tools):
        registry = build_software_agents()
        return [registry.get(role) for role in registry.roles()]

    def _inspect_requirements_task(self) -> SubTask:
        return SubTask(
            id="inspect_requirements",
            role="analyst",
            description="Read the requirement and record the expected behavior.",
            inputs=["requirements.md", "app.py"],
            max_retries=1,
            metadata={
                "workspace": WORKSPACE,
                "required_tools": ["file_editor"],
                "expected_outputs": ["artifacts/requirement_analysis.md"],
                "contract_criteria": ["requirement_analysis"],
                "checks": [
                    {
                        "id": "requirement_analysis",
                        "check_type": "file_exists",
                        "path": "artifacts/requirement_analysis.md",
                    }
                ],
            },
        )

    def _inspect_repository_task(self) -> SubTask:
        return SubTask(
            id="inspect_repository",
            role="architect",
            description="Inspect the fixture structure and record a minimal architecture note.",
            depends_on=["inspect_requirements"],
            inputs=["app.py", "test_app.py"],
            max_retries=1,
            metadata={
                "workspace": WORKSPACE,
                "required_tools": ["file_editor"],
                "expected_outputs": ["artifacts/architecture_design.md"],
                "contract_criteria": ["architecture_note"],
                "checks": [
                    {
                        "id": "architecture_note",
                        "check_type": "file_exists",
                        "path": "artifacts/architecture_design.md",
                    }
                ],
            },
        )

    def _diagnose_failure_task(self) -> SubTask:
        return SubTask(
            id="diagnose_failure",
            role="tester",
            description="Run the current tests and capture the failing baseline.",
            depends_on=["inspect_repository"],
            inputs=["test_app.py"],
            max_retries=0,
            metadata={
                "workspace": WORKSPACE,
                "required_tools": ["test_runner"],
            },
        )

    def _implement_fix_task(self) -> SubTask:
        return SubTask(
            id="implement_fix",
            role="developer",
            description="Repair app.py and prove the exact test command passes.",
            depends_on=["diagnose_failure"],
            inputs=["app.py", "test_app.py"],
            max_retries=2,
            metadata={
                "workspace": WORKSPACE,
                "required_tools": ["file_editor", "test_runner"],
                "expected_outputs": ["app.py"],
                "contract_criteria": ["source_updated", "pytest_pass"],
                "checks": [
                    {
                        "id": "source_updated",
                        "check_type": "file_exists",
                        "path": "app.py",
                    },
                    {
                        "id": "pytest_pass",
                        "check_type": "command",
                        "command": PYTEST_COMMAND,
                    },
                ],
            },
        )

    def _run_targeted_tests_task(self) -> SubTask:
        return SubTask(
            id="run_targeted_tests",
            role="tester",
            description="Run the exact regression command after the repair.",
            depends_on=["implement_fix"],
            inputs=["test_app.py"],
            max_retries=1,
            metadata={
                "workspace": WORKSPACE,
                "required_tools": ["test_runner"],
                "contract_criteria": ["pytest_pass"],
                "checks": [
                    {
                        "id": "pytest_pass",
                        "check_type": "command",
                        "command": PYTEST_COMMAND,
                    }
                ],
            },
        )

    def _build_change_report_task(self, *, depends_on=None) -> SubTask:
        return SubTask(
            id="build_change_report",
            role="reporter",
            description="Write a report containing the diff and test evidence.",
            depends_on=list(depends_on or []),
            inputs=["app.py"],
            max_retries=1,
            metadata={
                "workspace": WORKSPACE,
                "required_tools": ["file_editor"],
                "expected_outputs": [
                    "artifacts/software_report.md",
                    "artifacts/code_diff.patch",
                    "artifacts/test_log.txt",
                ],
                "contract_criteria": ["software_report_exists"],
                "checks": [
                    {
                        "id": "software_report_exists",
                        "check_type": "file_exists",
                        "path": "artifacts/software_report.md",
                    }
                ],
            },
        )

    def build_initial_plan(self, goal: str) -> Plan:
        """Phase 1: repair and test the fixture, intentionally leaving report evidence missing."""
        tasks = [
            self._inspect_requirements_task(),
            self._inspect_repository_task(),
            self._diagnose_failure_task(),
            self._implement_fix_task(),
            self._run_targeted_tests_task(),
        ]
        return Plan(
            goal=goal,
            subtasks=tasks,
            final_acceptance=[
                "source_updated",
                "pytest_pass",
                "software_report_exists",
            ],
        )

    def build_recovery_plan(self, goal: str, missing_criteria=None) -> Plan:
        """Phase 2: build the minimal recovery DAG for missing contract evidence."""
        missing = set(missing_criteria or ["software_report_exists"])
        tasks = []
        if "software_report_exists" in missing:
            tasks.append(self._build_change_report_task())
        return Plan(
            goal=goal,
            subtasks=tasks,
            final_acceptance=[
                "source_updated",
                "pytest_pass",
                "software_report_exists",
            ],
        )

    def build_plan(self, goal: str) -> Plan:
        """Single-phase smoke plan kept for contribution validation."""
        tasks = [
            self._inspect_requirements_task(),
            self._inspect_repository_task(),
            self._diagnose_failure_task(),
            self._implement_fix_task(),
            self._run_targeted_tests_task(),
            self._build_change_report_task(depends_on=["run_targeted_tests"]),
        ]
        return Plan(
            goal=goal,
            subtasks=tasks,
            final_acceptance=[
                "source_updated",
                "pytest_pass",
                "software_report_exists",
            ],
        )

    def build_contract(self, goal: str) -> AcceptanceContract:
        return AcceptanceContract(
            goal=goal,
            goal_summary="Repair the supplied buggy application and prove the exact test command passes.",
            criteria=[
                GoalCriterion(
                    id="source_updated",
                    description="The repaired source file exists and has current-run provenance.",
                    check_type="file_exists",
                    path="app.py",
                ),
                GoalCriterion(
                    id="regression_tests_exist",
                    description="The regression test file exists.",
                    check_type="file_exists",
                    path="test_app.py",
                ),
                GoalCriterion(
                    id="pytest_pass",
                    description="The exact pytest command exits with code 0.",
                    check_type="command",
                    command=PYTEST_COMMAND,
                ),
                GoalCriterion(
                    id="software_report_exists",
                    description="The final software report exists and has current-run provenance.",
                    check_type="file_exists",
                    path="artifacts/software_report.md",
                ),
            ],
            constraints=[
                "Do not rely on model prose as completion evidence.",
                "All required files and commands must be proven by current-run tool records.",
                "All file paths must remain inside the software fixture workspace.",
            ],
        )

    def reset_workspace(self, workspace):
        workspace = Path(workspace)
        workspace.mkdir(parents=True, exist_ok=True)
        artifacts = workspace / "artifacts"
        if artifacts.exists():
            shutil.rmtree(artifacts)
        artifacts.mkdir(parents=True, exist_ok=True)
        (workspace / "app.py").write_text(INITIAL_APP, encoding="utf-8")
        (workspace / "test_app.py").write_text(TEST_APP, encoding="utf-8")
        (workspace / "requirements.md").write_text(REQUIREMENTS, encoding="utf-8")
